### 2nd.exer
2nd exercise due to fail in 1st

print("Hello World")
